### ISSUE TITLE
How to individually access components?

### ISSUE THREAD

**Issue by shueja-personal** [NotionX/react-notion-x#130]
Hi, 
I am trying to customize the Notion-style header to include some additional JSX components. I planned to do this by creating a new header using the original as a template. However, the original uses PageIcon, SearchIcon, and SearchDialog, which do not seem to be exported outside the module, nor are any components besides ```code, collection, collection-row```. Is there a reason to not allow the other components to be individually imported and used perhaps in custom components to be passed back to NotionRenderer?

**Comment by nolantait** [comment]
I built out a small drop and replace library for exactly this so I could better customize the components: https://github.com/nolantait/notion-forge

You can feel free to use it or just pull inspiration from the way I rewrote the context: https://github.com/nolantait/notion-forge/blob/master/src/context.tsx

**Comment by n44ps** [comment]
Hey ! @nolantait, your library seems nice, however why not create a Pull Request here instead ?
Would @transitive-bullshit be interested in this ? It makes the renderer way more customizable :)

**Comment by transitive-bullshit** [comment]
v6 standardizes the way optional components are bundled and accessed. They each get their own separate bundle and can be loaded in isolation from each other and the main package bundle.

Currently, this is only for the larger components since it makes sense to keep the 95% use case in the main bundle.

If anyone has ideas for improving this design, I'd be happy to consider them.

Thanks!
