### ISSUE TITLE
Support for database Groups

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#152]
Notion just released a new feature that allows you to group databases based on any field.

More info: https://twitter.com/NotionHQ/status/1450512890738319361

If someone would like to take this on let me know and make a PR!

**Comment by hcorta** [comment]
@normdoow I'm currently working on this PR on parallel, but it's gonna take me some time due to the implications (both client/components are deeply affected) 😔. At this moment, I have the list collection almost 100% working, thought I'm facing some issues when grouping by certain elements (checkboxes, created_at...). No expectation to have in the short term, but I'll do my best.

**Comment by normdoow** [comment]
cool @hcorta! Thanks for letting me know.

**Comment by hcorta** [comment]
@normdoow first proposal ready for review #182

**Comment by normdoow** [comment]
This is now supported.
