### ISSUE TITLE
Error when importing NotionAPI from Notion-client in Next

### ISSUE THREAD

**Issue by Lucaslpena** [NotionX/react-notion-x#157]
I put the following lines in a simple component ```pages/index.js```

```
import { getPageTitle, getAllPagesInSpace } from 'notion-utils'
import { NotionAPI } from 'notion-client'
import { Collection, CollectionRow, NotionRenderer } from 'react-notion-x'
```

and I get the following error when running ```$yarn dev```:

```
error - ./node_modules/cacheable-lookup/source/index.js:10:2
Module not found: Can't resolve 'dns'

Import trace for requested module:
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/create.js
./node_modules/got/dist/source/index.js
./node_modules/notion-client/build/esm/notion-api.js
./node_modules/notion-client/build/esm/index.js
./pages/index.js

```

**Comment by dvdsgl** [comment]
I would love to just use the official Notion client to pull the block map to render with `react-notion-x`. We are really struggling with this error.

Alternatively, it would be great to move `notion-client` to an implementation that works in the client.

**Comment by MichaelCasaDev** [comment]
@Lucaslpena I think you are trying to import a server-side package (_"notion-client"_) into the client-side.
If you want to use the notion-client from the client you can use `getServerSideProps` method! _(for Next.JS)_

That's the list of packages and their usage.
![image](https://user-images.githubusercontent.com/57275048/140991015-6b7da4a8-8876-4700-8c14-9925d607ddb0.png)

**Comment by transitive-bullshit** [comment]
@MichaelCasaDev is correct; I believe the issue you're seeing is because you're trying to import and use the notion API client-side from the browser, which won't work fundamentally because of CORS issues. In this case, we're using the popular package `got` to handle fetching HTTP requests from notion's API which can only be called from Node.js.

The fix is to make sure you're only using `NotionAPI` from the server-side as in the [example next.js project](https://github.com/NotionX/react-notion-x/blob/master/example/pages/%5BpageId%5D.tsx), either via `getServerSideProps` or via `getStaticProps`.

**Comment by transitive-bullshit** [comment]
> I would love to just use the official Notion client to pull the block map to render with react-notion-x. We are really struggling with this error.

Note that this is not possible because notion's public API doesn't expose most block information — it's meant more for data / collection-related use cases, at least for the time being.

**Comment by wobsoriano** [comment]
If you want a temporary fix you could pass in a custom baseUrl with cors proxy to the client

```ts
const notion = new NotionCompatAPI(
  new Client({
    auth: process.env.NOTION_TOKEN,
    baseUrl: 'https://thingproxy.freeboard.io/fetch/https://api.notion.com'
  })
)
```

The main issue here is your Auth key being exposed to the browser.
