### ISSUE TITLE
Sidebar support

### ISSUE THREAD

**Issue by leonth** [NotionX/react-notion-x#167]
Is there any interest or prior effort in implementing the sidebar? For my use case I would love to be able to render the sidebar very similar to notion's so it can be the primary means of navigation between pages.

I would appreciate any pointers on how to implement this as well, if this is not something the project want to include in its scope.

**Comment by transitive-bullshit** [comment]
This library is pretty targeted at rendering a single page's contents. Rendering elements outside of a page are outside the scope of support.

In terms of a suggestion for implementing sidebar / workspace support, you would need to add some workspace fetching API functions to `notion-client` since right now all APIs are focused on fetching single-page content. I would start there, understand the notion data model for the workspace (by figuring out how notion's web API works when you view your workspace in the webapp via devtools), and only once you have the data for the workspace add your own react renderer outside of `react-notion-x` which renders the sidebar / workspace and uses `react-notion-x` to render individual pages.

Hope that helps 👍

**Comment by Gogeta999** [comment]
> Is there any interest or prior effort in implementing the sidebar? For my use case I would love to be able to render the sidebar very similar to notion's so it can be the primary means of navigation between pages.
> 
> I would appreciate any pointers on how to implement this as well, if this is not something the project want to include in its scope.

Nah, if you wanna use this package and customize by yourself, you can check my blog repo. **althought it is just a fun project** but might help a bit for you [here](https://github.com/Gogeta999/ash999). @leonth
