### ISSUE TITLE
Add support for using next/image

### ISSUE THREAD

**Issue by theodorepauw** [NotionX/react-notion-x#26]
Would it be possible to enable [Next's Image component](https://nextjs.org/docs/api-reference/next/image)?

This would bring [built-in optimization](https://nextjs.org/docs/basic-features/image-optimization) without an external CDN.

**Comment by transitive-bullshit** [comment]
Hey @theodorepauw, this is definitely on my bucket list, though it's not as easy as you would think. The main reason is that `next/image` currently isn't a drop-in replacement for `<img>` because it doesn't support most CSS styling.

The main difficulty is in making it possible to switch between different `Image` components and having CSS styling work gracefully between all of them, and with `next/image` containing multiple sub divs, this is difficult to do in practice.

Two related `next/image` issues are: https://github.com/vercel/next.js/issues/18858 and https://github.com/vercel/next.js/issues/18585, both of which I've commented on.

**Comment by theodorepauw** [comment]
I understand. Thanks for the swift response!

**Comment by TheMrZZ** [comment]
Hi!
NextJS implemented all necessary properties - would using `components.Image` instead of `GracefulImage` be possible now?

**Comment by transitive-bullshit** [comment]
Yep, this was added in #158 

We still need to document and add an example of this, though. Just set `components.Image` to `Image` from `next/image`.

**Comment by TheMrZZ** [comment]
It's not working - I already had `components.Image` set to `Image` from `next/image`, but it does not wrap any Notion image.

It's easy to notice: all `next/image` URLs start with `/_next/image?url=`, yet no image rendered by `react-notion-x` starts with it.

**Comment by eagor** [comment]
see https://github.com/NotionX/react-notion-x/issues/203#issuecomment-1041971729
