### ISSUE TITLE
notion-compat `getPage()` performance on private pages taking 2+ seconds to resolve

### ISSUE THREAD

**Issue by L0wry** [NotionX/react-notion-x#269]
#### Description

Hi team,

I understand this is a fairly new package so there may already be eyes on this. 
I have noticed it takes quite a long time for to get results from `new NotionCompatAPI(this.client).getPage(pageId)`

I've run a timer before and after the function and here are my results

```
Time to resolve: 2.340s
Time to resolve: 3.333s
Time to resolve: 2.778s
Time to resolve: 2.189s

```

#### Notion Test Page ID
It's private so unfortunately, I'm unable to provide one

#### Code
```
import { Client } from "@notionhq/client";
import { NotionCompatAPI } from 'notion-compat'

class NotionApi {
  constructor() {
    this.client = new Client({ auth: process.env.AUTH_SECRET })
    this.notionWrapper = new NotionCompatAPI(this.client)
  }

  getPage(pageId) {
    return this.notionWrapper.getPage(pageId);
  }
}
```
```
export async function getStaticProps(context) {
  const pageId = context.params?.id;
  if (!pageId) {
    return;
  }

  const notionClient = new NotionApi();
  console.time('Time to resolve');

  const blockMap = await notionClient.getPage(pageId);
  console.timeEnd('Time to resolve');

  return {
    props: {
      blockMap,
    },
    revalidate: 1
  };
}
```

**Comment by transitive-bullshit** [comment]
Unfortunately, I believe this is mainly due to poor API design by the official notion client, making it extremely tedious to fetch all blocks, sub-blocks, and indirect blocks needed to faithfully render a page.

I discuss this openly here: https://twitter.com/transitive_bs/status/1510747054921846787

Most non-trivial pages end up requiring 10+ API calls to Notion in order to fetch all the required blocks, whereas the private API requires 1 API call in most cases. This is something that only becomes apparent once you try to get the blocks for a page with the private API vs the public API and realize that the public API is missing a lot of data and block info.

For the logic handling this, see https://github.com/NotionX/react-notion-x/blob/master/packages/notion-compat/src/notion-compat-api.ts#L45 which is doing everything in our power to parallelize this by using `p-queue` with a default concurrency set to 4.

Very open to suggestions on how this logic could be improved. I've tried reaching out to Notion dev-rels to discuss this issue with the official API, but I haven't heard back :sigh:

**Comment by L0wry** [comment]
That is a shame but totally understandable. Either way thanks for an awesome library @transitive-bullshit! 
For anyone else looking at this, I've got around the performance issues using Next JS and their `getStaticProps` to pre-build all my notion pages.

**Comment by filipesmedeiros** [comment]
@transitive-bullshit I'm extremely curious about this. Why do you think the Notion team has built such a bad API? For sure they must have great engineers there. Do you think it's a business decision? They don't even provide webhooks 😢

**Comment by transitive-bullshit** [comment]
@filipesmedeiros my understanding is that it's due to two main factors:

1. Their business use cases are mainly focused around collections
2. Their fine-grained access controls make caching / bundling at the page level difficult

I still don't understand why the base case of fetching all blocks / sub-blocks for a page is so horrendously inefficient. It definitely seems like the type of 99% use case that could be solved by exposing a convenience wrapper on their end.

**Comment by filipesmedeiros** [comment]
@transitive-bullshit makes sense. I'm making a (simple) blog with their official API and haven't been rate limited yet. But I noticed that the URL that the API returns for file images expires... which is so lame but oh well.

Thanks!
