### ISSUE TITLE
Error Require() of ES Module not supported

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#277]
#### Description

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/noahbragg/Developer/node_projects/potion/potion-site-v2/node_modules/notion-utils/build/index.js from /Users/noahbragg/Developer/node_projects/potion/potion-site-v2/lib/config.ts not supported.
Instead change the require of index.js in /Users/noahbragg/Developer/node_projects/potion/potion-site-v2/lib/config.ts to a dynamic import() which is available in all CommonJS modules.

Im on the latest version of react-notion-x
"notion-client": "=6.12.0",
 "notion-types": "=6.11.0",
 "notion-utils": "=6.11.0",
 "react-notion-x": "=6.12.5",

Using  next v12.1.1

#### Notion Test Page ID

No page id. Just get this error when running any page that needs the notion-utils library.

**Comment by Commandtechno** [comment]
I had the same issue, but seems like this was intentional... Ended up switching to the dark side of ES6 today because of it.

Switched to module: https://github.com/NotionX/react-notion-x/commit/f114250ca41e1894a2cbb5ff16b97800f866e0a4
Removed CJS building: https://github.com/NotionX/react-notion-x/commit/4039b4e18848eb8dc0e3deb00a8245f24b534fc3

**Comment by transitive-bullshit** [comment]
I'm trying to move all of my NPM packages to focus on ESM support, [following Sindresorhus' lead](https://github.com/sindresorhus/meta/discussions/15).

If you're not sure how to consume ESM modules, see [this guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

I will consider re-adding commonjs support to react-notion-x *if* someone can provide a compelling reason why it's necessary. Otherwise, this change is intended to move the community towards ESM — which needs to happen sooner or later anyway.

**Comment by normdoow** [comment]
> I'm trying to move all of my NPM packages to focus on ESM support, [following Sindresorhus' lead](https://github.com/sindresorhus/meta/discussions/15).
> 
> If you're not sure how to consume ESM modules, see [this guide](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
> 
> I will consider re-adding commonjs support to react-notion-x _if_ someone can provide a compelling reason why it's necessary. Otherwise, this change is intended to help move the community towards ESM — which needs to happen sooner or later anyway.

hey, thanks for the info. I'm trying to follow the guide. Does https://github.com/transitive-bullshit/nextjs-notion-starter-kit  consume as ESM now as an example?

**Comment by transitive-bullshit** [comment]
> Does [transitive-bullshit/nextjs-notion-starter-kit](https://github.com/transitive-bullshit/nextjs-notion-starter-kit) consume as ESM now as an example?

Yes. All examples in this repo, as well as the accompanying starter kit have been switched to use ESM.

**Comment by normdoow** [comment]
Thanks @transitive-bullshit. I was just missing a piece of the ESM support in my project. After correctly upgrading everythign we are good to go. Closing for now.

**Comment by soullivaneuh** [comment]
@normdoow Are the fix you made released?

I still have the issue with a fresh install of `notion-client`

File:

```typescript
import { NotionAPI } from 'notion-client'

const notion = new NotionAPI({
  authToken: process.env.NOTION_API_KEY,
});
```

Causes:

```
❯ node src/run.js           
src/jobs/sprints.js:3
const notion_client_1 = require("notion-client");
                        ^

Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/notion-client/build/index.js from src/jobs/sprints.js not supported.
Instead change the require of index.js in src/jobs/sprints.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (src/jobs/sprints.js:3:25)
    at Object.<anonymous> (src/run.js:6:35) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.8.0
```
