### ISSUE TITLE
Untitled Pages Issue

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#29]
I had build issues when a page title is untitled. I believe react-notion-x is throwing an error in this case. I may be wrong about that. Could be in my own system.

These two pageIds has an untitled title. After giving them the build worked correctly.
d2a2831d28f74d8c9beee87f928f3d4e
d87f50f366994182b0037adb130f18f2

![image](https://user-images.githubusercontent.com/21371266/107803767-e8107480-6d17-11eb-8694-ef682b045783.png)

**Comment by transitive-bullshit** [comment]
Hey Noah 👋 

Will investigate this later today and get back to you.

**Comment by transitive-bullshit** [comment]
Hey @normdoow, I've checked both of these pages with `react-notion-x` as well as via my next.js example project with a blank page https://nextjs-notion-starter-kit-j6hau73b4.vercel.app/5995506f2c564d81956aa38711e12337 and haven't been able to reproduce any issues.

My guess is that it's probably an issue in your application above react-notion-x. Also, make sure your deps `notion-utils`, `notion-client`, `notion-types`, and `react-notion-x` are all up-to-date, because I have been fixing a lot of stuff over the past few weeks.

Otherwise, let me know if you have a better repro scenario that I can look at.

**Comment by normdoow** [comment]
Thanks! Yeah, Looks like this is on my side.
