### ISSUE TITLE
Image height extends Notion block - doesn't look quite like Notion.

### ISSUE THREAD

**Issue by normdoow** [NotionX/react-notion-x#34]
@transitive-bullshit I saw you made a change to image height a few commits ago. Trying to understand what the change was for. But I did notice that since then some images have a height that makes them  extend the space vertically. Looks different then Notion does. 

Here is an example from https://www.notion.so/cerdeira/Hey-I-m-Nico-34712887699841fab1b59e404ba9d73a

With react-notion-x
![image](https://user-images.githubusercontent.com/21371266/109100701-41927f00-76da-11eb-85a3-3e0367498e64.png)

With notion:
![image](https://user-images.githubusercontent.com/21371266/109100763-5a029980-76da-11eb-91ed-55e35d9f5d01.png)

I can make a fix for this. Just wanted to understand your thinking behind the change.

**Comment by transitive-bullshit** [comment]
This is definitely a bug in `react-notion-x` that's due to us trying to reverse-engineer all the combinations of ways that notion image assets and their `format` properties can be defined.

Here's where to look in the code https://github.com/NotionX/react-notion-x/blob/master/packages/react-notion-x/src/components/asset.tsx#L53

And here's a good test page to make sure that any changes don't have unintended consequences: https://react-notion-x-demo.transitivebullsh.it/image-sizing-3492bd6dbaf44fe7a5cac62c5d402f06

**Comment by normdoow** [comment]
Fix here: https://github.com/NotionX/react-notion-x/pull/35

**Comment by transitive-bullshit** [comment]
Fixed by #35
