### ISSUE TITLE
Feature Request: Support for notion-sdk-js

### ISSUE THREAD

**Issue by jzzfs** [NotionX/react-notion-x#354]
#### Description

The package [currently uses `token_v2`](https://github.com/NotionX/react-notion-x/blob/bf81f2aa75c60b785e850b363901f47b9a2cd464/packages/notion-client/src/notion-api.ts#L591) to access Notion's servers. These tokens tend to expire upon logout so are there any plans to add support for the [official JS SDK](https://github.com/makenotion/notion-sdk-js)?

If yes, is there an epic to contribute to? Thanks!

#### Notion Test Page ID

N/A

**Comment by transitive-bullshit** [comment]
See https://github.com/NotionX/react-notion-x/issues/66 and #256 for more discussion around supporting the official API.

Note that the official API uses a very different block and API structure and has a lot of drawbacks including being significantly slower and not supporting all block types. I'm hoping these issues will be addressed by the Notion team over time, but the current best effort at a compatibility layer is in the [notion-compat](https://github.com/NotionX/react-notion-x/tree/master/packages/notion-compat) package which is more of a proof of concept at the moment than a real replacement for `notion-client`.

In terms of fully supporting the official Notion API, this would require a large rewrite of `notion-client`, `notion-types`, and `react-notion-x`. It has not been considered yet because of the aforementioned tradeoffs (you can dig into the issues above to see more details).

**Comment by jzzfs** [comment]
Thanks & consider this closed.
