### ISSUE TITLE
The example don't run very well

### ISSUE THREAD

**Issue by Mvbbb** [NotionX/react-notion-x#56]
I cloned this repo, and did not modify anything. Then I try  run the example in localhost, but the collections disappeared. 
![image](https://user-images.githubusercontent.com/56795364/115649523-120a9680-a35a-11eb-9f6d-94eaa9631258.png)

Is this because I skipped some essential steps ?

**Comment by normdoow** [comment]
Hey @Mvbbb, 

So collections aren't used by default in the example. We could probably add this to the example since I would guess most people would want them. You actually have to add them in the `components` param on `NotionRenderer`

Import it
```
import { Collection, CollectionRow, NotionRenderer } from 'react-notion-x'
```

Add it here in `components`.
```
<NotionRenderer recordMap={recordMap} fullPage={true} darkMode={false} components={{
  collection: Collection,
  collectionRow: CollectionRow
}} />
```
Hope this helps. and maybe we will add this by default for the example.

**Comment by transitive-bullshit** [comment]
Hey @Mvbbb, for larger components like collections, you need to opt into them as they're not bundled by default.

https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/components/NotionPage.tsx#L15

**Comment by transitive-bullshit** [comment]
Thanks @normdoow 💯
